#!/usr/bin/env python3
"""gen_fw_blob.py — Convert a firmware binary file to a C header.

Generates a C header containing a const uint8_t array with the firmware
bytes.  Used by the build system to bake the HP LaserJet 1020 (or 1015/1022)
EZ-USB firmware blob directly into the firmware image so the print server can
upload it to the printer automatically at power-on with no user action.

Usage:
    python3 gen_fw_blob.py <input_fw_file> <output_header.h>

Arguments:
    input_fw_file    Path to the firmware binary (.dl, .img, .fw, or Intel HEX)
    output_header.h  Path to write the generated C header

Generated symbols (in the header):
    hp1020_fw_blob[]      const uint8_t array of firmware bytes
    HP1020_FW_BLOB_SIZE   size_t length constant (sizeof(hp1020_fw_blob))

The generated header is designed to be included exactly once, from
usb_printer.c when compiled with -DHAVE_HP1020_FW_BUILTIN.
"""

import sys
import os


def generate_header(fw_path: str, out_path: str) -> None:
    with open(fw_path, "rb") as f:
        data = f.read()

    n = len(data)
    if n == 0:
        raise ValueError(f"Firmware file '{fw_path}' is empty")

    src_name = os.path.basename(fw_path)
    guard = "GPSU21_HP1020_FW_BLOB_H"

    # Format bytes as C hex literals, 16 per line
    hex_lines = []
    for i in range(0, n, 16):
        chunk = data[i : i + 16]
        hex_lines.append("    " + ", ".join(f"0x{b:02x}u" for b in chunk))

    with open(out_path, "w") as f:
        f.write(
            f"/*\n"
            f" * hp1020_fw_blob.h — HP LaserJet 1020 EZ-USB firmware blob\n"
            f" *\n"
            f" * Auto-generated by gen_fw_blob.py from:\n"
            f" *   {src_name}  ({n} bytes)\n"
            f" *\n"
            f" * The firmware binary is HP-proprietary.  This header is generated\n"
            f" * at build time from a locally-supplied file and is NOT committed\n"
            f" * to the repository.\n"
            f" *\n"
            f" * Include this header from usb_printer.c only when compiled with\n"
            f" *   -DHAVE_HP1020_FW_BUILTIN\n"
            f" */\n"
            f"\n"
            f"#ifndef {guard}\n"
            f"#define {guard}\n"
            f"\n"
            f"#include <stdint.h>\n"
            f"#include <stddef.h>\n"
            f"\n"
            f"/* {n} bytes from {src_name} */\n"
            f"/* This header is designed to be included exactly once,\n"
            f" * from usb_printer.c when compiled with -DHAVE_HP1020_FW_BUILTIN. */\n"
            f"const uint8_t hp1020_fw_blob[{n}u] = {{\n"
        )
        f.write(",\n".join(hex_lines))
        f.write(
            f"\n"
            f"}};\n"
            f"\n"
            f"/* Use a macro for the size so it can be used in constant expressions */\n"
            f"#define HP1020_FW_BLOB_SIZE  ({n}u)\n"
            f"\n"
            f"#endif /* {guard} */\n"
        )

    print(f"gen_fw_blob: wrote {n} bytes → {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <firmware_file> <output_header.h>",
              file=sys.stderr)
        sys.exit(1)
    generate_header(sys.argv[1], sys.argv[2])
