#!/usr/bin/env python3
"""
gen_web_resources.py — Generate web_resources.c from a directory of web files.

This script scans the gpsu21_web/ directory (or any directory given as the
first argument) and produces a C source file that embeds every file as a
static const uint8_t array.  The resulting web_resources[] table is used by
httpd.c to serve the web UI directly from ROM (flash), with no filesystem
needed at runtime.

Usage:
    python3 gen_web_resources.py  <web_dir>  <output.c>

Example:
    python3 firmware/src/gen_web_resources.py  gpsu21_web/  build/web_resources.c
"""

import sys
import os

# MIME-type index values used by the stock ZOT firmware.
# httpd.c uses these to select the Content-Type header.
MIME_INDEX = {
    ".htm":  1,
    ".html": 1,
    ".js":   2,
    ".css":  3,
    ".jpg":  4,
    ".jpeg": 4,
    ".gif":  5,
    ".png":  6,
    ".ico":  7,
}

def c_identifier(path):
    """Convert a relative path like 'images/foo.jpg' to a C identifier."""
    return path.replace("/", "_").replace(".", "_").replace("-", "_")


def generate(web_dir, output_path):
    # Collect all files (recursively for images/)
    entries = []
    for root, _dirs, files in os.walk(web_dir):
        for filename in sorted(files):
            if filename == "manifest.txt":
                continue
            full   = os.path.join(root, filename)
            reldir = os.path.relpath(root, web_dir)
            if reldir == ".":
                relpath = filename
            else:
                relpath = reldir.replace("\\", "/") + "/" + filename
            with open(full, "rb") as f:
                data = f.read()
            ext   = os.path.splitext(filename)[1].lower()
            mtype = MIME_INDEX.get(ext, 0)
            entries.append((relpath, data, mtype))

    with open(output_path, "w", encoding="utf-8") as out:
        out.write("/* web_resources.c — auto-generated by gen_web_resources.py\n")
        out.write(" * DO NOT EDIT — regenerate with:\n")
        out.write(f" *   python3 firmware/src/gen_web_resources.py  {web_dir}  {output_path}\n")
        out.write(" */\n\n")
        out.write("#include <stdint.h>\n")
        out.write("#include <stddef.h>\n")
        out.write("#include <string.h>\n")
        out.write("#include \"web_resources.h\"\n\n")

        # Emit each file as a static byte array
        for relpath, data, _mtype in entries:
            ident = c_identifier(relpath)
            out.write(f"static const uint8_t _data_{ident}[] = {{\n")
            for i in range(0, len(data), 16):
                chunk = data[i:i+16]
                hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
                out.write(f"    {hex_vals},\n")
            out.write("};\n\n")

        # Emit the resource table
        out.write("const web_resource_t web_resources[] = {\n")
        for relpath, data, mtype in entries:
            ident = c_identifier(relpath)
            out.write(f'    {{ "{relpath}", _data_{ident}, {len(data)}u, {mtype}u }},\n')
        out.write("};\n\n")

        # Count
        out.write(f"const unsigned int web_resource_count = {len(entries)}u;\n\n")

        # Lookup function
        out.write("""
const web_resource_t *web_resource_find(const char *name)
{
    unsigned int i;
    for (i = 0; i < web_resource_count; i++) {
        if (strcmp(web_resources[i].name, name) == 0) {
            return &web_resources[i];
        }
    }
    return NULL;
}
""")

    print(f"Generated {output_path} with {len(entries)} resources "
          f"({sum(len(d) for _, d, _ in entries):,} bytes total)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    generate(sys.argv[1], sys.argv[2])
