/*
 * httpd.c — Minimal HTTP server for the IOGear GPSU21 print server firmware.
 *
 * This server serves the web interface files that are stored in the ROM file
 * table (generated by gen_web_resources.py from the gpsu21_web/ directory).
 *
 * Key stability fix vs. stock firmware:
 *   The auto-refresh <meta> tags in INDEX.HTM and SERVICES.HTM have been
 *   removed from the source HTML files (see gpsu21_web/).  This prevents
 *   browser tabs from opening new HTTP connections every 5–10 seconds and
 *   exhausting the 36-connection lwIP TCP pool (Finding 1 in README).
 *
 * Architecture:
 *   - Listens on TCP port 80.
 *   - Handles up to HTTP_MAX_CONNECTIONS simultaneous connections by
 *     dispatching each to its own child thread from a pre-allocated pool.
 *   - Serves static files from the web_resources table (web_resources.c).
 *   - POST /save_settings and POST /upgrade are handled separately.
 */

#include "rtos.h"

#include <lwip/sockets.h>
#include <lwip/inet.h>
#include <lwip/def.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#include "httpd.h"
#include "web_resources.h"
#include "config.h"
#include "usb_printer.h"

/* ─────────────────────────────────────────────────────────────────────────────
 * Configuration
 * ───────────────────────────────────────────────────────────────────────────*/
#define HTTP_PORT               80
#define HTTP_MAX_CONNECTIONS    8
#define HTTP_RECV_BUF_SIZE      2048
#define HTTP_SEND_BUF_SIZE      4096
/*
 * HTTP_THREAD_STACK_SIZE — stack for each per-connection child thread, in bytes.
 *
 * handle_request() places char buf[HTTP_RECV_BUF_SIZE] (2048 B) and
 * char lower[128] on the stack, plus call-frame overhead and lwIP internal
 * usage (lwip_recv → lwip_send).  Measured worst-case depth is ~3 200 B;
 * 8 192 B gives a comfortable safety margin.
 *
 * Halving this to 4 096 B was the previous value and leaves only ~900 B of
 * headroom after locals, which is insufficient when lwIP adds its own frames.
 * A stack overflow there silently corrupts memory and can brick the device.
 */
#define HTTP_THREAD_STACK_SIZE  8192
#define HTTP_THREAD_PRIORITY    12

/* ─────────────────────────────────────────────────────────────────────────────
 * Per-connection child thread pool
 * ───────────────────────────────────────────────────────────────────────────*/
typedef struct {
    int             fd;
    cyg_bool_t      in_use;
    cyg_handle_t    thread;
    /*
     * NOTE: thread stack and TCB are allocated dynamically by xTaskCreate so
     * that FreeRTOS frees them via the idle task after vTaskDelete(NULL).
     *
     * The previous implementation used xTaskCreateStatic with a StaticTask_t
     * and stack[] array embedded here.  That caused a race condition: after a
     * child called vTaskDelete(NULL), FreeRTOS placed the StaticTask_t on the
     * internal xTasksWaitingTermination list; if a new connection reused the
     * same slot before the idle task processed that list, xTaskCreateStatic
     * would overwrite the StaticTask_t's xStateListItem, corrupting the
     * FreeRTOS scheduler's task lists and crashing the device.
     */
} http_conn_t;

static http_conn_t http_pool[HTTP_MAX_CONNECTIONS];
static cyg_mutex_t http_pool_lock;

/* ─────────────────────────────────────────────────────────────────────────────
 * MIME type table
 * ───────────────────────────────────────────────────────────────────────────*/
typedef struct {
    const char *ext;
    const char *mime;
} mime_entry_t;

static const mime_entry_t mime_table[] = {
    { ".htm",  "text/html"       },
    { ".html", "text/html"       },
    { ".js",   "text/javascript" },
    { ".css",  "text/css"        },
    { ".jpg",  "image/jpeg"      },
    { ".jpeg", "image/jpeg"      },
    { ".gif",  "image/gif"       },
    { ".png",  "image/png"       },
    { ".ico",  "image/x-icon"    },
    { NULL,    "application/octet-stream" },
};

static const char *get_mime(const char *filename)
{
    const mime_entry_t *e;
    const char *dot = strrchr(filename, '.');

    if (!dot) {
        return "application/octet-stream";
    }
    for (e = mime_table; e->ext != NULL; e++) {
        if (strcasecmp(dot, e->ext) == 0) {
            return e->mime;
        }
    }
    return mime_table[sizeof(mime_table)/sizeof(mime_table[0]) - 1].mime;
}

/* ─────────────────────────────────────────────────────────────────────────────
 * HTTP response helpers
 * ───────────────────────────────────────────────────────────────────────────*/
static void send_response(int fd, int status, const char *status_msg,
                          const char *mime, const void *body, size_t body_len)
{
    char hdr[256];
    int  hdr_len;

    hdr_len = snprintf(hdr, sizeof(hdr),
        "HTTP/1.0 %d %s\r\n"
        "Content-Type: %s\r\n"
        "Content-Length: %zu\r\n"
        "Connection: close\r\n"
        "\r\n",
        status, status_msg, mime, body_len);

    lwip_send(fd, hdr, (size_t)hdr_len, 0);
    if (body && body_len > 0) {
        lwip_send(fd, (void *)body, body_len, 0);
    }
}

static void send_404(int fd)
{
    static const char body[] = "<html><body><h1>404 Not Found</h1></body></html>";
    send_response(fd, 404, "Not Found", "text/html",
                  body, sizeof(body) - 1);
}

static void send_200_file(int fd, const char *filename,
                          const void *data, size_t len)
{
    send_response(fd, 200, "OK", get_mime(filename), data, len);
}

/* ─────────────────────────────────────────────────────────────────────────────
 * URL-decode a percent-encoded string in-place (+ → space, %XX → byte).
 * ───────────────────────────────────────────────────────────────────────────*/
static void url_decode(char *dst, const char *src, size_t dst_size)
{
    size_t i = 0;
    while (*src && i < dst_size - 1) {
        if (*src == '+') {
            dst[i++] = ' ';
            src++;
        } else if (*src == '%' && src[1] && src[2]) {
            unsigned int hex = 0;
            const char *h = src + 1;
            /* Parse two hex digits manually (avoids sscanf overhead). */
            if (*h >= '0' && *h <= '9')      hex  = (unsigned)(*h - '0') << 4;
            else if (*h >= 'A' && *h <= 'F') hex  = (unsigned)(*h - 'A' + 10) << 4;
            else if (*h >= 'a' && *h <= 'f') hex  = (unsigned)(*h - 'a' + 10) << 4;
            h++;
            if (*h >= '0' && *h <= '9')      hex |= (unsigned)(*h - '0');
            else if (*h >= 'A' && *h <= 'F') hex |= (unsigned)(*h - 'A' + 10);
            else if (*h >= 'a' && *h <= 'f') hex |= (unsigned)(*h - 'a' + 10);
            dst[i++] = (char)hex;
            src += 3;
        } else {
            dst[i++] = *src++;
        }
    }
    dst[i] = '\0';
}

/* ─────────────────────────────────────────────────────────────────────────────
 * Parse a URL query string and apply known settings.
 *
 * Recognised parameters (all others are silently ignored):
 *   PSName          — device / AirPrint service instance name
 *   AirPrintEnabled — "0" disables AirPrint advertising, "1" enables it
 *   ScannerEnabled  — "0" disables AirScan (eSCL) advertising, "1" enables it
 * ───────────────────────────────────────────────────────────────────────────*/
static void parse_and_apply_settings(const char *query)
{
    char qs[512];
    char *token;
    char decoded[CONFIG_DEVICE_NAME_MAX];

    strncpy(qs, query, sizeof(qs) - 1);
    qs[sizeof(qs) - 1] = '\0';

    token = strtok(qs, "&");
    while (token) {
        char *eq  = strchr(token, '=');
        char *key;
        char *value;
        if (eq) {
            *eq   = '\0';
            key   = token;
            value = eq + 1;

            if (strcmp(key, "PSName") == 0) {
                url_decode(decoded, value, sizeof(decoded));
                config_set_device_name(decoded);
            } else if (strcmp(key, "AirPrintEnabled") == 0) {
                config_set_airprint_enabled(atoi(value));
            } else if (strcmp(key, "ScannerEnabled") == 0) {
                config_set_scanner_enabled(atoi(value));
            }
        }
        token = strtok(NULL, "&");
    }
}

/* ─────────────────────────────────────────────────────────────────────────────
 * Request handler — called from each child thread
 * ───────────────────────────────────────────────────────────────────────────*/
static void handle_request(int fd)
{
    char buf[HTTP_RECV_BUF_SIZE];
    int  n;
    char method[8], path[128], proto[16];
    const web_resource_t *res;
    const char *filename;

    /* Read the request line */
    n = lwip_recv(fd, buf, sizeof(buf) - 1, 0);
    if (n <= 0) {
        return;
    }
    buf[n] = '\0';

    if (sscanf(buf, "%7s %127s %15s", method, path, proto) < 2) {
        send_404(fd);
        return;
    }

    /* If the path contains a query string (e.g. /restart.htm?PSName=Foo&...),
     * extract and apply the settings, then serve only the bare filename. */
    {
        char *qs = strchr(path, '?');
        if (qs) {
            *qs = '\0';                      /* isolate the filename */
            parse_and_apply_settings(qs + 1);
        }
    }

    /* Normalise path: "/" → "/index.htm" */
    filename = path;
    if (strcmp(path, "/") == 0) {
        filename = "/index.htm";
    }
    /* Strip leading '/' */
    if (filename[0] == '/') {
        filename++;
    }

    /* ── /api/printer_status — JSON endpoint for the printer status page ── *
     * Returns a JSON object with the live printer state derived from the USB
     * back-channel (GET_PORT_STATUS) and other fields from g_printer_status. */
    if (strcmp(filename, "api/printer_status") == 0) {
        char json[512];
        int  json_len;

        json_len = snprintf(json, sizeof(json),
            "{"
            "\"connected\":%s,"
            "\"online\":%s,"
            "\"paper_empty\":%s,"
            "\"error\":%s,"
            "\"busy\":%s,"
            "\"needs_firmware\":%s,"
            "\"jobs_printed\":%lu,"
            "\"bytes_sent\":%lu,"
            "\"device_id\":\"%s\""
            "}",
            g_printer_status.connected    ? "true"  : "false",
            g_printer_status.online       ? "true"  : "false",
            g_printer_status.paper_empty  ? "true"  : "false",
            g_printer_status.error        ? "true"  : "false",
            g_printer_status.busy         ? "true"  : "false",
            g_printer_status.needs_firmware ? "true" : "false",
            (unsigned long)g_printer_status.jobs_printed,
            (unsigned long)g_printer_status.bytes_sent,
            (const char *)g_printer_status.device_id);

        send_response(fd, 200, "OK", "application/json", json, (size_t)json_len);
        return;
    }

    /* ── GET /api/printer_fw_status — firmware blob storage status ──────── */
    if (strcmp(filename, "api/printer_fw_status") == 0) {
        char json[64];
        int  json_len = snprintf(json, sizeof(json),
            "{\"has_blob\":%s,\"size\":%u}",
            usb_fw_has_blob() ? "true" : "false",
            (unsigned)usb_fw_blob_size());
        send_response(fd, 200, "OK", "application/json",
                      json, (size_t)json_len);
        return;
    }

    /* ── POST /api/upload_printer_fw — store firmware blob for EZ-USB upload
     *
     * Accepts the HP LaserJet 1020 (or 1015/1022) printer firmware as a raw
     * POST body.  Two file formats are supported:
     *   Intel HEX  — HPLIP's hp_laserjet_1020.fw (first byte is ':')
     *   Raw binary — foo2zjs's sihp1020.img (any other first byte)
     *
     * The firmware binary is HP-proprietary; obtain it from:
     *   - HPLIP: /usr/share/hplip/data/firmware/hp_laserjet_1020.fw
     *   - foo2zjs: firmware/sihp1020.img
     *
     * Example:
     *   curl -X POST http://<ip>/api/upload_printer_fw \
     *        --data-binary @hp_laserjet_1020.fw
     *
     * On success returns: {"ok":true,"bytes":<n>}
     * ─────────────────────────────────────────────────────────────────── */
    if (strcmp(method, "POST") == 0 &&
        strcmp(filename, "api/upload_printer_fw") == 0) {

        /* Parse Content-Length from the already-received request headers */
        const char *cl_hdr = strstr(buf, "Content-Length:");
        if (!cl_hdr) cl_hdr = strstr(buf, "content-length:");
        if (!cl_hdr) {
            static const char err[] = "{\"error\":\"Content-Length required\"}";
            send_response(fd, 411, "Length Required", "application/json",
                          err, sizeof(err) - 1);
            return;
        }
        int content_length = atoi(cl_hdr + 15);
        if (content_length <= 0 || (size_t)content_length > USB_FW_MAX_SIZE) {
            static const char err[] =
                "{\"error\":\"invalid Content-Length (must be 1–65536)\"}";
            send_response(fd, 413, "Content Too Large", "application/json",
                          err, sizeof(err) - 1);
            return;
        }

        /* Locate start of body in the already-received buffer.
         * The HTTP request line + headers end at the first \r\n\r\n. */
        const char *body_start = strstr(buf, "\r\n\r\n");
        int body_in_buf = 0;
        if (body_start) {
            body_start += 4;
            body_in_buf = n - (int)(body_start - buf);
            if (body_in_buf < 0) body_in_buf = 0;
        }

        /* Receive firmware data directly into the fw blob buffer to avoid
         * a second copy.  usb_fw_get_write_buf() returns a pointer to the
         * static 64 KB buffer; no large stack allocation is needed here. */
        size_t   max_fw;
        uint8_t *fw_buf = usb_fw_get_write_buf(&max_fw);

        /* Copy the body bytes already in buf into the fw buffer */
        size_t total = 0;
        if (body_in_buf > 0 && body_start) {
            memcpy(fw_buf, body_start, (size_t)body_in_buf);
            total = (size_t)body_in_buf;
        }

        /* Stream the remainder of the body directly into fw_buf */
        while ((int)total < content_length) {
            int to_read = content_length - (int)total;
            if (to_read > HTTP_RECV_BUF_SIZE) to_read = HTTP_RECV_BUF_SIZE;
            int rcv = lwip_recv(fd, fw_buf + total, (size_t)to_read, 0);
            if (rcv <= 0) break;
            total += (size_t)rcv;
        }

        if ((int)total < content_length) {
            static const char err[] = "{\"error\":\"incomplete upload\"}";
            send_response(fd, 400, "Bad Request", "application/json",
                          err, sizeof(err) - 1);
            return;
        }

        /* Commit the blob — from now on the status thread will use it */
        usb_fw_commit(total);

        char resp[64];
        int  resp_len = snprintf(resp, sizeof(resp),
                                 "{\"ok\":true,\"bytes\":%u}",
                                 (unsigned)total);
        send_response(fd, 200, "OK", "application/json",
                      resp, (size_t)resp_len);
        return;
    }
    res = web_resource_find(filename);
    if (res) {
        send_200_file(fd, res->name, res->data, res->size);
    } else {
        /* Check with lowercased name (the stock firmware is case-insensitive) */
        char lower[128];
        size_t i;
        strncpy(lower, filename, sizeof(lower) - 1);
        lower[sizeof(lower) - 1] = '\0';
        for (i = 0; lower[i]; i++) {
            if (lower[i] >= 'A' && lower[i] <= 'Z') {
                lower[i] = (char)(lower[i] + 32);
            }
        }
        res = web_resource_find(lower);
        if (res) {
            send_200_file(fd, res->name, res->data, res->size);
        } else {
            send_404(fd);
        }
    }
}

/* ─────────────────────────────────────────────────────────────────────────────
 * Child-thread entry point
 * ───────────────────────────────────────────────────────────────────────────*/
static void http_child_thread(void *arg)
{
    http_conn_t *conn = (http_conn_t *)arg;

    handle_request(conn->fd);
    lwip_close(conn->fd);

    cyg_mutex_lock(&http_pool_lock);
    conn->in_use = false;
    cyg_mutex_unlock(&http_pool_lock);

    cyg_thread_exit();
}

/* ─────────────────────────────────────────────────────────────────────────────
 * HTTP server main thread
 * ───────────────────────────────────────────────────────────────────────────*/
void httpd_thread(void *arg)
{
    int                server_fd;
    int                client_fd;
    struct sockaddr_in addr;
    int                opt = 1;
    cyg_uint32         i;

    (void)arg;

    cyg_mutex_init(&http_pool_lock);
    memset(http_pool, 0, sizeof(http_pool));

    server_fd = lwip_socket(AF_INET, SOCK_STREAM, 0);
    if (server_fd < 0) {
        diag_printf("httpd: socket() failed\n");
        return;
    }
    lwip_setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    memset(&addr, 0, sizeof(addr));
    addr.sin_family      = AF_INET;
    addr.sin_port        = htons(HTTP_PORT);
    addr.sin_addr.s_addr = INADDR_ANY;

    if (lwip_bind(server_fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        diag_printf("httpd: bind() failed\n");
        lwip_close(server_fd);
        return;
    }
    if (lwip_listen(server_fd, HTTP_MAX_CONNECTIONS) < 0) {
        diag_printf("httpd: listen() failed\n");
        lwip_close(server_fd);
        return;
    }

    diag_printf("httpd: listening on port %d\n", HTTP_PORT);

    for (;;) {
        http_conn_t *slot = NULL;

        client_fd = lwip_accept(server_fd, NULL, NULL);
        if (client_fd < 0) {
            diag_printf("httpd: accept() failed\n");
            cyg_thread_delay(10);
            continue;
        }

        /* Find a free slot in the connection pool */
        cyg_mutex_lock(&http_pool_lock);
        for (i = 0; i < HTTP_MAX_CONNECTIONS; i++) {
            if (!http_pool[i].in_use) {
                slot = &http_pool[i];
                slot->in_use = true;
                slot->fd     = client_fd;
                break;
            }
        }
        cyg_mutex_unlock(&http_pool_lock);

        if (!slot) {
            /* No free slot — log and close.  The stock firmware logs:
             * "http:1216, No free socket!" at this point.  We do the same
             * but do not leave the socket open (which was the original bug). */
            diag_printf("httpd: No free socket!\n");
            lwip_close(client_fd);
            continue;
        }

        {
            BaseType_t ret;
            ret = xTaskCreate(
                http_child_thread,
                "http_child",
                (configSTACK_DEPTH_TYPE)(HTTP_THREAD_STACK_SIZE / sizeof(StackType_t)),
                (void *)slot,
                CYG_TO_FRT_PRIO(HTTP_THREAD_PRIORITY),
                &slot->thread);
            if (ret != pdPASS) {
                diag_printf("httpd: xTaskCreate failed (out of heap?)\n");
                lwip_close(client_fd);
                cyg_mutex_lock(&http_pool_lock);
                slot->in_use = false;
                cyg_mutex_unlock(&http_pool_lock);
                continue;
            }
        }
    }
}
