/*
 * httpd.c — Minimal HTTP server for the IOGear GPSU21 print server firmware.
 *
 * This server serves the web interface files that are stored in the ROM file
 * table (generated by gen_web_resources.py from the gpsu21_web/ directory).
 *
 * Key stability fix vs. stock firmware:
 *   The auto-refresh <meta> tags in INDEX.HTM and SERVICES.HTM have been
 *   removed from the source HTML files (see gpsu21_web/).  This prevents
 *   browser tabs from opening new HTTP connections every 5–10 seconds and
 *   exhausting the 36-connection lwIP TCP pool (Finding 1 in README).
 *
 * Architecture:
 *   - Listens on TCP port 80.
 *   - Handles up to HTTP_MAX_CONNECTIONS simultaneous connections by
 *     dispatching each to its own child thread from a pre-allocated pool.
 *   - Serves static files from the web_resources table (web_resources.c).
 *   - POST /save_settings and POST /upgrade are handled separately.
 */

#include <cyg/kernel/kapi.h>
#include <cyg/infra/diag.h>

#include <lwip/sockets.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#include "httpd.h"
#include "web_resources.h"

/* ─────────────────────────────────────────────────────────────────────────────
 * Configuration
 * ───────────────────────────────────────────────────────────────────────────*/
#define HTTP_PORT               80
#define HTTP_MAX_CONNECTIONS    8
#define HTTP_RECV_BUF_SIZE      2048
#define HTTP_SEND_BUF_SIZE      4096
#define HTTP_THREAD_STACK_SIZE  4096
#define HTTP_THREAD_PRIORITY    12

/* ─────────────────────────────────────────────────────────────────────────────
 * Per-connection child thread pool
 * ───────────────────────────────────────────────────────────────────────────*/
typedef struct {
    int             fd;
    cyg_bool_t      in_use;
    cyg_handle_t    thread;
    cyg_thread      thread_obj;
    char            stack[HTTP_THREAD_STACK_SIZE];
} http_conn_t;

static http_conn_t http_pool[HTTP_MAX_CONNECTIONS];
static cyg_mutex_t http_pool_lock;

/* ─────────────────────────────────────────────────────────────────────────────
 * MIME type table
 * ───────────────────────────────────────────────────────────────────────────*/
typedef struct {
    const char *ext;
    const char *mime;
} mime_entry_t;

static const mime_entry_t mime_table[] = {
    { ".htm",  "text/html"       },
    { ".html", "text/html"       },
    { ".js",   "text/javascript" },
    { ".css",  "text/css"        },
    { ".jpg",  "image/jpeg"      },
    { ".jpeg", "image/jpeg"      },
    { ".gif",  "image/gif"       },
    { ".png",  "image/png"       },
    { ".ico",  "image/x-icon"    },
    { NULL,    "application/octet-stream" },
};

static const char *get_mime(const char *filename)
{
    const mime_entry_t *e;
    const char *dot = strrchr(filename, '.');

    if (!dot) {
        return "application/octet-stream";
    }
    for (e = mime_table; e->ext != NULL; e++) {
        if (strcasecmp(dot, e->ext) == 0) {
            return e->mime;
        }
    }
    return mime_table[sizeof(mime_table)/sizeof(mime_table[0]) - 1].mime;
}

/* ─────────────────────────────────────────────────────────────────────────────
 * HTTP response helpers
 * ───────────────────────────────────────────────────────────────────────────*/
static void send_response(int fd, int status, const char *status_msg,
                          const char *mime, const void *body, size_t body_len)
{
    char hdr[256];
    int  hdr_len;

    hdr_len = snprintf(hdr, sizeof(hdr),
        "HTTP/1.0 %d %s\r\n"
        "Content-Type: %s\r\n"
        "Content-Length: %zu\r\n"
        "Connection: close\r\n"
        "\r\n",
        status, status_msg, mime, body_len);

    send(fd, hdr, (size_t)hdr_len, 0);
    if (body && body_len > 0) {
        send(fd, body, body_len, 0);
    }
}

static void send_404(int fd)
{
    static const char body[] = "<html><body><h1>404 Not Found</h1></body></html>";
    send_response(fd, 404, "Not Found", "text/html",
                  body, sizeof(body) - 1);
}

static void send_200_file(int fd, const char *filename,
                          const void *data, size_t len)
{
    send_response(fd, 200, "OK", get_mime(filename), data, len);
}

/* ─────────────────────────────────────────────────────────────────────────────
 * Request handler — called from each child thread
 * ───────────────────────────────────────────────────────────────────────────*/
static void handle_request(int fd)
{
    char buf[HTTP_RECV_BUF_SIZE];
    int  n;
    char method[8], path[128], proto[16];
    const web_resource_t *res;
    const char *filename;

    /* Read the request line */
    n = recv(fd, buf, sizeof(buf) - 1, 0);
    if (n <= 0) {
        return;
    }
    buf[n] = '\0';

    if (sscanf(buf, "%7s %127s %15s", method, path, proto) < 2) {
        send_404(fd);
        return;
    }

    /* Normalise path: "/" → "/index.htm" */
    filename = path;
    if (strcmp(path, "/") == 0) {
        filename = "/index.htm";
    }
    /* Strip leading '/' */
    if (filename[0] == '/') {
        filename++;
    }

    /* Look up the file in the ROM resource table */
    res = web_resource_find(filename);
    if (res) {
        send_200_file(fd, res->name, res->data, res->size);
    } else {
        /* Check with lowercased name (the stock firmware is case-insensitive) */
        char lower[128];
        size_t i;
        strncpy(lower, filename, sizeof(lower) - 1);
        lower[sizeof(lower) - 1] = '\0';
        for (i = 0; lower[i]; i++) {
            if (lower[i] >= 'A' && lower[i] <= 'Z') {
                lower[i] = (char)(lower[i] + 32);
            }
        }
        res = web_resource_find(lower);
        if (res) {
            send_200_file(fd, res->name, res->data, res->size);
        } else {
            send_404(fd);
        }
    }
}

/* ─────────────────────────────────────────────────────────────────────────────
 * Child-thread entry point
 * ───────────────────────────────────────────────────────────────────────────*/
static void http_child_thread(cyg_addrword_t arg)
{
    http_conn_t *conn = (http_conn_t *)arg;

    handle_request(conn->fd);
    close(conn->fd);

    cyg_mutex_lock(&http_pool_lock);
    conn->in_use = false;
    cyg_mutex_unlock(&http_pool_lock);

    cyg_thread_exit();
}

/* ─────────────────────────────────────────────────────────────────────────────
 * HTTP server main thread
 * ───────────────────────────────────────────────────────────────────────────*/
void httpd_thread(cyg_addrword_t arg)
{
    int                server_fd;
    int                client_fd;
    struct sockaddr_in addr;
    int                opt = 1;
    cyg_uint32         i;

    (void)arg;

    cyg_mutex_init(&http_pool_lock);
    memset(http_pool, 0, sizeof(http_pool));

    server_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (server_fd < 0) {
        diag_printf("httpd: socket() failed\n");
        return;
    }
    setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    memset(&addr, 0, sizeof(addr));
    addr.sin_family      = AF_INET;
    addr.sin_port        = htons(HTTP_PORT);
    addr.sin_addr.s_addr = INADDR_ANY;

    if (bind(server_fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        diag_printf("httpd: bind() failed\n");
        close(server_fd);
        return;
    }
    if (listen(server_fd, HTTP_MAX_CONNECTIONS) < 0) {
        diag_printf("httpd: listen() failed\n");
        close(server_fd);
        return;
    }

    diag_printf("httpd: listening on port %d\n", HTTP_PORT);

    for (;;) {
        http_conn_t *slot = NULL;

        client_fd = accept(server_fd, NULL, NULL);
        if (client_fd < 0) {
            diag_printf("httpd: accept() failed\n");
            cyg_thread_delay(10);
            continue;
        }

        /* Find a free slot in the connection pool */
        cyg_mutex_lock(&http_pool_lock);
        for (i = 0; i < HTTP_MAX_CONNECTIONS; i++) {
            if (!http_pool[i].in_use) {
                slot = &http_pool[i];
                slot->in_use = true;
                slot->fd     = client_fd;
                break;
            }
        }
        cyg_mutex_unlock(&http_pool_lock);

        if (!slot) {
            /* No free slot — log and close.  The stock firmware logs:
             * "http:1216, No free socket!" at this point.  We do the same
             * but do not leave the socket open (which was the original bug). */
            diag_printf("httpd: No free socket!\n");
            close(client_fd);
            continue;
        }

        cyg_thread_create(
            HTTP_THREAD_PRIORITY,
            http_child_thread,
            (cyg_addrword_t)slot,
            "http_child",
            slot->stack,
            HTTP_THREAD_STACK_SIZE,
            &slot->thread,
            &slot->thread_obj
        );
        cyg_thread_resume(slot->thread);
    }
}
