/*
 * web_resources.h — ROM file table for the GPSU21 HTTP server.
 *
 * The table and data arrays are generated automatically from the gpsu21_web/
 * directory by gen_web_resources.py.  Do not edit this file by hand.
 */
#ifndef WEB_RESOURCES_H
#define WEB_RESOURCES_H

#include <stddef.h>

typedef struct {
    const char    *name;   /* filename, e.g. "index.htm" or "images/foo.jpg" */
    const uint8_t *data;   /* pointer to file content */
    size_t         size;   /* byte length */
    unsigned int   type;   /* MIME-type index (same encoding as stock firmware) */
} web_resource_t;

/* Find a resource by filename (case-sensitive).
 * Returns a pointer into the static table, or NULL if not found. */
const web_resource_t *web_resource_find(const char *name);

/* Total number of entries in the table. */
extern const unsigned int web_resource_count;

/* The resource table itself (defined in web_resources.c). */
extern const web_resource_t web_resources[];

#endif /* WEB_RESOURCES_H */
